apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: contact-ingress
 namespace: contact
spec:
 rules:
 - host: 
   http:
     paths:
     - path:/contact-svc.about.svc.cluster.local
       backend:
         serviceName: contact-svc
         servicePort: 80
